### ISSUE TITLE
Cannot find module './index.node'

### ISSUE THREAD

**Issue by danhumphrey** [sondr3/astro-html-minifier#4]
I'm getting a 'Cannot find module' error when attempting to use this package in my astro project.

I get the same errors as reported in #3, although this issue was closed without resolution. I'm on a brand new mac with a fresh install of node/npm - I even tried downgrading versions a number of times, but this package fails every time: 

```
> astro dev

node:internal/modules/cjs/loader:956
  const err = new Error(message);
              ^

Error: Cannot find module './index.node'
Require stack:
- /Users/dan/projects/new-leaf/node_modules/@minify-html/node/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Function.Module._load (node:internal/modules/cjs/loader:804:27)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/dan/projects/new-leaf/node_modules/@minify-html/node/index.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/dan/projects/new-leaf/node_modules/@minify-html/node/index.js'
  ]
}
```

If I comment out the import statement and remove the integration from my `astro.config.mjs` file, then I can build without error.

Any suggestions? I'll be very happy to help debug and resolve this as I would prefer not to have to remove the integration from the project.

**Comment by sondr3** [comment]
Just a small heads-up, Astro now natively supports HTML minification as part of the build process: https://astro.build/blog/astro-250/#html-minification. So this integration might not be needed, I haven't checked the builtin minification to compare yet. Which version of `@minify-html/node` and `astro-html-minifier` are you using? I had a similar update that I thought I fixed in the recent version bump.

**Comment by danhumphrey** [comment]
That's awesome, thanks @sondr3 - I didn't realise minification was now built in!!

I had previously tried versions `0.5.0` and `0.4.1` without success, but also just tried `0.3.0` and got the same error, but I think I'll remove it and go native. If you decide to persist with this and want help debugging a future version, I'm happy to help.

Thanks!

**Comment by sondr3** [comment]
Unless you really want to use this, I don't think it's worth it, I've been considering sunsetting this package now that it is included by default in Astro 😃 The only reason I can think that this fails is because the `postinstall`-script fails/doesn't run for `@minify-html/node`, maybe you're missing `cargo` or have set an option in `~/.npmrc`? I'll close this issue, but let me know if you want to move back to this integration in the future.
